In [3]:
"""
This file contains code that will kick off training and testing processes
"""
import os
import json

from experiments.UNetExperiment import UNetExperiment
from data_prep.HippocampusDatasetLoader import LoadHippocampusData

class Config:
    """
    Holds configuration parameters
    """
    def __init__(self):
        self.name = "Basic_unet"
        self.root_dir = r"/home/workspace/src/TrainingSet/"
        self.n_epochs = 1
        self.learning_rate = 0.00005
        self.batch_size = 16
        self.patch_size = 64
        self.test_results_dir = "/home/workspace/src/results/"

Matplotlib is building the font cache using fc-list. This may take a moment.


In [4]:
if __name__ == "__main__":
    # Get configuration

    # TASK: Fill in parameters of the Config class and specify directory where the data is stored and 
    # directory where results will go
    c = Config()

    # Load data
    print("Loading data...")

    # TASK: LoadHippocampusData is not complete. Go to the implementation and complete it. 
    data = LoadHippocampusData(c.root_dir, y_shape = c.patch_size, z_shape = c.patch_size)


    # Create test-train-val split
    # In a real world scenario you would probably do multiple splits for 
    # multi-fold training to improve your model quality

    keys = range(len(data))

    # Here, random permutation of keys array would be useful in case if we do something like 
    # a k-fold training and combining the results. 

    split = dict()

    # TASK: create three keys in the dictionary: "train", "val" and "test". In each key, store
    # the array with indices of training volumes to be used for training, validation 
    # and testing respectively.
    split['train'] = keys[0:int(0.7*len(keys))] # 70% training data
    split['val'] = keys[int(0.7*len(keys)):int(0.9*len(keys))] # 20% validation data
    split['test'] = keys[int(0.9*len(keys)):] # 10% testing dat

    # Set up and run experiment
    assert(not bool(set(split['train']) & set(split['val'])))
    assert(not bool(set(split['val']) & set(split['test'])))
    # TASK: Class UNetExperiment has missing pieces. Go to the file and fill them in
    exp = UNetExperiment(c, split, data)

    # You could free up memory by deleting the dataset
    # as it has been copied into loaders
    # del dataset 

    # run training
    exp.run()

    # prep and run testing

    # TASK: Test method is not complete. Go to the method and complete it
    results_json = exp.run_test()

    results_json["config"] = vars(c)

    with open(os.path.join(exp.out_dir, "results.json"), 'w') as out_file:
        json.dump(results_json, out_file, indent=2, separators=(',', ': '))


Loading data...
Processed 260 files, total 9198 slices
Experiment started.
Training epoch 0...

Epoch: 0 Train loss: 1.210514783859253, 0.2% complete
..........
Epoch: 0 Train loss: 1.1967532634735107, 2.7% complete
..........
Epoch: 0 Train loss: 1.1804296970367432, 5.2% complete
..........
Epoch: 0 Train loss: 1.1529120206832886, 7.7% complete
..........
Epoch: 0 Train loss: 1.0597305297851562, 10.2% complete
..........
Epoch: 0 Train loss: 0.2008616328239441, 12.7% complete
..........
Epoch: 0 Train loss: 0.0018720789812505245, 15.2% complete
..........
Epoch: 0 Train loss: 0.00016371862147934735, 17.7% complete
..........
Epoch: 0 Train loss: 5.010771565139294e-05, 20.1% complete
..........
Epoch: 0 Train loss: 2.9694288969039917e-05, 22.6% complete
..........
Epoch: 0 Train loss: 2.400350058451295e-05, 25.1% complete
..........
Epoch: 0 Train loss: 2.2025080397725105e-05, 27.6% complete
..........
Epoch: 0 Train loss: 2.1212734282016754e-05, 30.1% complete
..........
Epoch: 0 Trai

Batch 68. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 69. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 70. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 71. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 72. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 73. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 74. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 75. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 76. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 77. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 78. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 79. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05
Batch 80. Data shape torch.Size([16, 1, 64, 64]) Loss 1.4842080418020487e-05


 testing inside the i loop dc [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]

 testing inside the i loop dc [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0


 testing inside the i loop dc [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]

 testing inside the i loop dc [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0

TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'